apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app: {{ .Values.nameOverride }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.nameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PORT
              value: {{ .Values.service.targetPort | quote }}

          {{- if .Values.envFile.enabled }}
          volumeMounts:
            {{- if .Values.envFile.existingSecretName }}
            - name: envfile-existing-secret
              mountPath: {{ .Values.envFile.mountPath }}
              subPath: .env
              readOnly: true
            {{- else if gt (len .Values.envFile.secret) 0 }}
            - name: envfile-secret
              mountPath: {{ .Values.envFile.mountPath }}
              subPath: .env
              readOnly: true
            {{- else if gt (len .Values.envFile.config) 0 }}
            - name: envfile-config
              mountPath: {{ .Values.envFile.mountPath }}
              subPath: .env
              readOnly: true
            {{- end }}
          {{- end }}

      {{- if .Values.envFile.enabled }}
      volumes:
        {{- if .Values.envFile.existingSecretName }}
        - name: envfile-existing-secret
          secret:
            secretName: {{ .Values.envFile.existingSecretName }}
        {{- else if gt (len .Values.envFile.secret) 0 }}
        - name: envfile-secret
          secret:
            secretName: "{{ .Values.nameOverride }}-env-secret"
        {{- else if gt (len .Values.envFile.config) 0 }}
        - name: envfile-config
          configMap:
            name: "{{ .Values.nameOverride }}-env"
        {{- end }}
      {{- end }}
